// import { StaticImage } from "gatsby-plugin-image"
import * as React from "react"

import Layout from "../components/Layout"
import { NftHistory } from "../components/NftHistory"
import { PlaceBid } from "../components/placeBid"
import { ProfileCard } from "../components/profileCard/profileCard"
import Seo from "../components/seo"

const nftDetails2 = () => (
  <Layout authenticated={false}>
    <Seo title="nftDetails" />
    <div className="flex flex-wrap w-full max-w-screen-2xl justify-center max-h-screen 2xl:mx-auto m-0 content-box">
      <div className="flex-grow  flex flex-col items-center">
        <div className="max-w-2xl max-h-3xl md:px-12 px-6  md:py-8 py-6 content-box ">
          <img
            className="object-contain max-h-full rounded-md"
            // src={`placeholder.png`}
            src="https://img.rarible.com/prod/image/upload/prod-itemImages/0xf6793da657495ffeff9ee6350824910abc21356c:75494182886653729428604749835760476447679257830022697915037882677082732888065/8bef717d"            loading="lazy"
            alt="nft image"
          />
        </div>
      </div>
      <div className="pt-5 md:pl-4 sm:pl-5 px-2 space-y-4  w-99 max-h-screen flex flex-col justify-between box-border">
        <div className="space-y-5">
          <div className="flex md:space-x-10 sm:space-x-8 space-x-2  justify-start items-center mb-4">
            <div className="space-y-2">
              <h1 className="font-sans font-bold md:text-xl text-base">Owned by</h1>
              <ProfileCard />
            </div>
            <div className="space-y-2">
              <h1 className="  font-sans font-bold md:text-xl text-base">Collection</h1>
              <ProfileCard />
            </div>
          </div>
          <p className="font-sans font-bold md:text-3xl text-2xl">
            BASTARD GAN PUNK V2 #10699
          </p>
          <p className="font-sans font-bold text-xl">
            Description
          </p>
          <p className="font-sans font-medium text-base max-w-xs">
            Each Soccer Doge is algorithmically generated by combining more than 100 attributes of different rarities in 10 categories (fur, background, eyes, mouth, nose, shirt, hat, earrings, necklace and beard).        </p>
        </div>

        <div className="max-w-lg space-y-5">
        {/* <h1 className="font-sans font-bold md:text-xl text-base">Bidded</h1> */}
        {/* <h1 className="font-sans font-bold md:text-xl text-base">Not Bidded</h1> */}
        {/* <h1 className="font-sans font-bold md:text-xl text-base">Buy Now</h1> */}

          <PlaceBid />
        </div>

      </div>

    </div>
  </Layout>
)

export default nftDetails2
